repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python -m pytest
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
