repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: /home/jolivier/miniconda3/envs/gomoku/bin/python -m pytest
        language: system
        types: [python]
        always_run: true
        pass_filenames: false
