[project]
name = "gomoku"
version = "0.1.0"
readme = "README.md"
requires-python = "==3.11.*"

dependencies = [
    "pandas>=2.2.0",
    "numpy>=1.26.3",
    "matplotlib>=3.8.2",
    "pygame>=2.6.1",
    "pytest>=8.3.4",
]

[tool.setuptools]
packages = ["src"]